<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="amitkambli" failures="2" tests="2" name="parallel.FailedRun" time="34.263" errors="0" timestamp="08 May 2024 14:02:26 GMT" skipped="0">
  <testcase classname="parallel.FailedRun" name="runScenario" time="20.890">
    <failure message="this test is designed to fail to check rerun of failed tests" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: this test is designed to fail to check rerun of failed tests
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at parallel.AccountPageSteps.user_is_on_accounts_page(AccountPageSteps.java:40)
at ✽.user is on Accounts page(file:///C:/Users/amitm/eclipse-workspace/CucumberSeries/src/test/resources/parallel/AccountPage.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="parallel.FailedRun" name="runScenario" time="13.373">
    <failure message="this test is designed to fail to check rerun of failed tests" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: this test is designed to fail to check rerun of failed tests
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at parallel.AccountPageSteps.user_is_on_accounts_page(AccountPageSteps.java:40)
at ✽.user is on Accounts page(file:///C:/Users/amitm/eclipse-workspace/CucumberSeries/src/test/resources/parallel/AccountPage.feature:17)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- parallel.FailedRun -->
